name: Flutter CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"

      - name: Instalar dependências
        run: flutter pub get

      - name: Fazer build do APK (debug)
        run: flutter build apk --debug

      - name: Fazer upload do APK como artefato
        uses: actions/upload-artifact@v4
        with:
          name: arquivo-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
